Repository ElsiKora/ESLint-Config, pull requests merged in 2025-03, with the labels that each got.

#166 Dev
  package.json
Labels: released on @beta

#170 Dev
  package.json
  src/infrastructure/config/next.ts
Labels: released on @beta

#192 Dev
  package.json
Labels: released on @beta

#216 Dev
  package.json
  src/infrastructure/config/i18next.ts
  src/test/unit/infrastructure/config/i18next.test.ts
Labels: Review effort 2/5

#218 chore(typescript): support uppercase boolean prefixes in naming rules
  src/infrastructure/config/typescript.ts
Labels: Review effort 1/5
